services:
  - type: web
    name: keiba-club
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 8000
      - key: SECRET_TOKEN
        generateValue: true
